baseURL = "https://ai-ue-o.jp/"
languageCode = "en-us"
title = "AI-UE-O"
theme = "hugo-theme-bootstrap"

[params]
  description = "This is the AI-UE-O website"
  author = "Your Name"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2